### ISSUE TITLE
README.md update

### ISSUE THREAD

**Issue by jppope** [dandynaufaldi/Agendernet#3]
Hi there, 

(wonderful project by the way) So I was wondering if you could update the readme to add steps to reproduce your results. despite the script being well organized thus far I've been unable to reproduce your work. My guess is that I'm missing a step

thank you

**Comment by dandynaufaldi** [comment]
> Hi there,
> 
> (wonderful project by the way) So I was wondering if you could update the readme to add steps to reproduce your results. despite the script being well organized thus far I've been unable to reproduce your work. My guess is that I'm missing a step
> 
> thank you

Could you mention which part that you hope to be clearer?. Thanks
