### ISSUE TITLE
: cannot connect to X server  pure virtual method called terminate called without an active exception Aborted (core dumped)

### ISSUE THREAD

**Issue by niushaoda** [dandynaufaldi/Agendernet#4]
: cannot connect to X server 
pure virtual method called
terminate called without an active exception
Aborted (core dumped)

**Comment by dandynaufaldi** [comment]
> : cannot connect to X server
> pure virtual method called
> terminate called without an active exception
> Aborted (core dumped)

have u tried too use X11 forwarding?

xhost +local:docker
XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth

sudo rm -rf /tmp/.docker.xauth
sudo touch /tmp/.docker.xauth

sudo xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
sudo nvidia-docker run -it --privileged --rm --env QT_X11_NO_MITSHM=1 -e DISPLAY=$DISPLAY \
    -v $XSOCK:$XSOCK \
    -v $XAUTH:$XAUTH \
    -e XAUTHORITY=$XAUTH \
    **-v ~/Documents/git:/git \\**  
    --name nvidia dandynaufaldi/tf-keras-cuda8-cudnn6-cpu

change the bold text as your volume mounting point
